# Generated by Django 3.1.4 on 2021-02-03 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='test_test'),
            preserve_default=False,
        ),
    ]
